# Generated by Django 4.2 on 2023-05-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_p', models.CharField(max_length=255, unique=True, verbose_name='Название Проекта')),
                ('description_p', models.TextField(null=True, verbose_name='Текст статьи')),
                ('time_create_p', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update_p', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published_p', models.BooleanField(default=False, null=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': '1. Проекты',
                'ordering': ['-time_create_p', 'title_p'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_s', models.CharField(max_length=255, verbose_name='Раздел Проекта')),
                ('time_create_s', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update_s', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published_s', models.BooleanField(default=False, null=True, verbose_name='Публикация')),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Раздел проекта',
                'verbose_name_plural': '2. Разделы проекта',
                'ordering': ['title_s'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_w', models.CharField(max_length=255, verbose_name='Вид Работы')),
                ('time_create_w', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update_w', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('quantity_w', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_w', models.CharField(help_text='Введите короткое название единицы измерения (максимум 10 символов). Пример:кв.м', max_length=10, verbose_name='Единица измерения')),
                ('margin_w', models.PositiveIntegerField(verbose_name='Наценка')),
                ('sect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.projectsection', verbose_name='Вид работы')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': '3. Вид работ',
                'ordering': ['title_w'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_r', models.CharField(choices=[('P', 'Люди'), ('T', 'Техника'), ('M', 'Материалы или Оборудование'), ('O', 'Накладные расходы')], max_length=30, null=True, verbose_name='Ресурс')),
                ('time_create_r', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update_r', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('quantity_r', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('day_cost_r', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость за день')),
                ('unit_cost_r', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость за единицу')),
                ('unit_r', models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица измерения')),
                ('cost_r', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость накладных')),
                ('overhead_r', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование накладной')),
                ('prj_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.project', verbose_name='Проект')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.worktype', verbose_name='Вид работы')),
            ],
            options={
                'verbose_name': 'Тип ресурса',
                'verbose_name_plural': '4. Типы Ресурсов',
                'ordering': ['title_r'],
            },
        ),
    ]
