# Generated by Django 4.2 on 2023-05-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_p',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published_p',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='is_published_s',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Публикация'),
        ),
    ]
