# Generated by Django 4.2 on 2023-05-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0005_worktype_prj_w'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='prj_w',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='sect',
        ),
    ]
