# Generated by Django 4.2 on 2023-05-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0006_remove_worktype_prj_w_remove_worktype_sect'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='prj_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimate.project', verbose_name='Проект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktype',
            name='sect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimate.projectsection', verbose_name='Вид работы'),
            preserve_default=False,
        ),
    ]
