# Generated by Django 4.2 on 2023-05-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0007_worktype_prj_w_worktype_sect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cost_r',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма затрат'),
        ),
    ]
