# Generated by Django 4.2 on 2023-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0008_alter_resource_cost_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title_r',
            field=models.CharField(choices=[('p', 'Люди'), ('t', 'Техника'), ('m', 'Материалы или Оборудование'), ('o', 'Накладные расходы')], max_length=30, null=True, verbose_name='Ресурс'),
        ),
    ]
