# Generated by Django 4.2 on 2023-05-31 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0009_alter_resource_title_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='sect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.projectsection', verbose_name='Секция проекта'),
        ),
    ]
