# Generated by Django 4.2 on 2023-06-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0010_alter_worktype_sect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsection',
            options={'ordering': ['-time_create_s'], 'verbose_name': 'Раздел проекта', 'verbose_name_plural': '2. Разделы проекта'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-time_create_r'], 'verbose_name': 'Тип ресурса', 'verbose_name_plural': '4. Типы Ресурсов'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ['-time_create_w'], 'verbose_name': 'Вид работы', 'verbose_name_plural': '3. Вид работ'},
        ),
    ]
