# Generated by Django 4.2 on 2023-06-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0011_alter_projectsection_options_alter_resource_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsection',
            options={'ordering': ['-title_s'], 'verbose_name': 'Раздел проекта', 'verbose_name_plural': '2. Разделы проекта'},
        ),
    ]
